version: '3'
services:
  prometheus:
    image: prom/prometheus
    privileged: true
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./disk.rules:/prometheus/disk.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - monitoring
    restart: always  

  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'
    networks:
      - monitoring
    restart: always
    
  alertmanager:
    image: prom/alertmanager
    privileged: true
    ports:
      - '9093:9093'
    networks:
    - monitoring
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=camptocamp-prometheus-alertmanager-datasource
    networks:
      - monitoring
    restart: always

networks:
  monitoring:
